@echo off

set COSMOS=third_party\cosmos\bin
set MAKECOSMOS=third_party/cosmos/bin
set SUBMAKECOSMOS=../cosmos/bin
set SHELL=sh
set CC=x86_64-unknown-cosmo-cc
set CXX=x86_64-unknown-cosmo-c++

%COSMOS%\make.exe %* SHELL=%MAKECOSMOS%/%SHELL% PATH=%MAKECOSMOS% SUBMAKESHELL=SHELL=%SUBMAKECOSMOS%/%SHELL% SUBMAKEPATH=PATH=%SUBMAKECOSMOS% CC="%MAKECOSMOS%/%SHELL% %MAKECOSMOS%/%CC%" CXX="%MAKECOSMOS%/%SHELL% %MAKECOSMOS%/%CXX%" SUBMAKECC=CC="\"%SUBMAKECOSMOS%/%SHELL% %SUBMAKECOSMOS%/%CC%\""
