#ifndef PCGAME_GDIFRONTEND_H
#define PCGAME_GDIFRONTEND_H

#define GAMEDATA 100
#define GAMEDATA_TYPE RCDATA

#ifdef _WIN32
#define GAMEDATA_RESTYPE RT_RCDATA
#else
#define GAMEDATA_RESTYPE 0
#endif

#endif // PCGAME_GDIFRONTEND_H
